import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="showcase">
        <br />

        <Link href="/birthday" passHref>
          <a>Project 1</a>
        </Link>

        <br />
        <br />
        <Link href="/tours">
          <a>Project 2</a>
        </Link>
      </div>
    </>
  );
}
